### knime-postgres-operator ClusterRole and ClusterRoleBinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knime-postgres-operator
rules:
# The postgres-operator requires node read access to check nodes for a readiness label.
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
# to read existing PVs. Creation should be done via dynamic provisioning.
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update # only for resizing AWS volumes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knime-postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knime-postgres-operator
subjects:
  # Important: The name and namespace of this ServiceAccount
  # is fixed and may not be changed here.
- kind: ServiceAccount
  name: knime-postgres-operator
  namespace: knime

### Role and RoleBinding used by services for license validation.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-metadata-reader
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-namespace-uid-reader-rolebinding
  namespace: kube-system
roleRef:
  kind: Role
  name: namespace-metadata-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: license-checker
    namespace: knime
  - kind: ServiceAccount
    name: secret-store
    namespace: knime
  - kind: ServiceAccount
    name: catalog-service
    namespace: knime
  - kind: ServiceAccount
    name: accounts-service
    namespace: knime
  - kind: ServiceAccount
    name: rest-interface
    namespace: knime
  - kind: ServiceAccount
    name: search-service
    namespace: knime
